name: pure.international.snackskitty.customer
description: Cat food delivery application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #UI/UX
  flutter_spinkit: ^5.0.0
  loading_overlay: ^0.3.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  rflutter_alert: ^2.0.2
  flutter_rating_bar: ^4.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0

  #GetX
  get: ^4.0.0-nullsafety.2
  get_storage: ^2.0.1

  #date
  intl: ^0.17.0

  #network
  #connectivity: ^3.0.2
  app_settings: ^4.1.0
  permission_handler: ^6.0.1+1
  flutter_local_notifications: ^5.0.0-nullsafety.1
  graphql_flutter: ^5.0.0-nullsafety.1
  cached_network_image: ^3.0.0-nullsafety

  #ui insurance
  logger: ^1.0.0-nullsafety.0

  flutter_launcher_icons: ^0.9.0

  #Firebase
  ##firebase_core: ^1.0.1
  ##firebase_auth: ^1.0.1
  ##firebase_storage: ^8.0.0
  ##cloud_firestore: ^1.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/paw.jpg"
    ##--> REPLACE THE app-icon.png FILE IN ASSET/IMAGE AND THEN <--##
    ##--> RUN BELOW CODE TO CHANGE THE APP ICON <--##
    #flutter pub get
    #flutter pub run flutter_launcher_icons:main


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/

  fonts:
    - family: PottaOne-Regular
      fonts:
        - asset: assets/fonts/PottaOne-Regular.ttf
    - family: PermanentMarker-Regular
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
    - family: Grandstander
      fonts:
        - asset: assets/fonts/Grandstander-Regular.ttf